name: Android CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace



  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
     
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      
      - name: Check APK vulnerabilities
        run: |
          sudo apt-get update && sudo apt-get install -yq python3-dev python3-venv python3-pip build-essential libffi-dev libssl-dev libxml2-dev libxslt1-dev libjpeg8-dev zlib1g-dev wkhtmltopdf
          git clone https://github.com/MobSF/Mobile-Security-Framework-MobSF.git
          APP_NAME=app-debug.apk
          APP_PATH="app/build/outputs/apk/debug/${APP_NAME}"
          APP_HASH=`md5sum $APP_PATH | awk '{print $1}'`
          cd Mobile-Security-Framework-MobSF
          MOBSF_API_KEY=`./setup.sh 2>&1 | grep REST | awk '{print $4}'| tail -1`
          ./run.sh &
          sleep 1
          cd ..
          curl -F 'file=@'"${APP_PATH}" http://localhost:8000/api/v1/upload -H "Authorization:${MOBSF_API_KEY}"
          curl -X POST --url http://localhost:8000/api/v1/scan --data "scan_type=apk&file_name=${APP_NAME}&hash=${APP_HASH}" -H "Authorization:${MOBSF_API_KEY}"
          curl -X POST --url http://localhost:8000/api/v1/download_pdf --data "hash=${APP_HASH}" -H "Authorization:${MOBSF_API_KEY}" > ~/report.pdf
          rm -rf mobsfpy
          kill `ps aux | grep gunicorn | awk '{print $2}' | head -1`
  
      - name: Upload qark report
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report.pdf

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
